services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    ports:
      - "8099:80"
    environment:
      - TELEGRAM_BOT_TOKEN=8961024375:AAF36dkRNCxdmNfANxBdU-dx6JTPFo93pKo
      - TELEGRAM_CHAT_ID=5073300049
      - PUBLIC_URL=YOUR_PUBLIC_HTTPS_URL_HERE
    restart: always
